Thu Feb 18 19:02:21 CST 2021
make[1]: Entering directory '/sources/Python-3.9.1'
LD_LIBRARY_PATH=/sources/Python-3.9.1 CC='gcc -pthread' LDSHARED='gcc -pthread -shared    ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall' 	_TCLTK_INCLUDES='' _TCLTK_LIBS='' 	./python -E ./setup.py  build
running build
running build_ext
INFO: Can't locate Tcl/Tk libs and/or headers

Python build finished successfully!
The necessary bits to build these optional modules were not found:
_sqlite3              _tkinter              nis                
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
_abc                  atexit                pwd                
time                                                           

running build_scripts
copying and adjusting /sources/Python-3.9.1/Tools/scripts/pydoc3 -> build/scripts-3.9
copying and adjusting /sources/Python-3.9.1/Tools/scripts/idle3 -> build/scripts-3.9
copying and adjusting /sources/Python-3.9.1/Tools/scripts/2to3 -> build/scripts-3.9
changing mode of build/scripts-3.9/pydoc3 from 664 to 775
changing mode of build/scripts-3.9/idle3 from 664 to 775
changing mode of build/scripts-3.9/2to3 from 664 to 775
renaming build/scripts-3.9/pydoc3 to build/scripts-3.9/pydoc3.9
renaming build/scripts-3.9/idle3 to build/scripts-3.9/idle3.9
renaming build/scripts-3.9/2to3 to build/scripts-3.9/2to3-3.9
LD_LIBRARY_PATH=/sources/Python-3.9.1 ./python -E -c 'import sys ; from sysconfig import get_platform ; print("%s-%d.%d" % (get_platform(), *sys.version_info[:2]))' >platform
LD_LIBRARY_PATH=/sources/Python-3.9.1 ./python  ./Tools/scripts/run_tests.py 
== CPython 3.9.1 (default, Feb 18 2021, 19:03:26) [GCC 10.2.0]
== Linux-5.8.3-lfs-10.1-rc1-x86_64-with-glibc2.33 little-endian
== cwd: /sources/Python-3.9.1/build/test_python_1863Ã¦
== CPU count: 24
== encodings: locale=UTF-8, FS=utf-8
Using random seed 2814035
0:00:00 load avg: 1.01 Run tests in parallel using 26 child processes
0:00:00 load avg: 1.01 [  1/425] test_xdrlib passed
0:00:00 load avg: 1.01 [  2/425] test_idle skipped
test_idle skipped -- No module named '_tkinter'
0:00:00 load avg: 1.01 [  3/425] test_super passed
0:00:00 load avg: 1.01 [  4/425] test_keywordonlyarg passed
0:00:00 load avg: 1.01 [  5/425] test_codecencodings_hk passed
0:00:00 load avg: 1.01 [  6/425] test_positional_only_arg passed
0:00:00 load avg: 1.01 [  7/425] test_contextlib_async passed
Task was destroyed but it is pending!
task: <Task pending name='Task-9' coro=<<async_generator_athrow without __name__>()>>
Task was destroyed but it is pending!
task: <Task pending name='Task-11' coro=<<async_generator_athrow without __name__>()>>
Task was destroyed but it is pending!
task: <Task pending name='Task-16' coro=<<async_generator_athrow without __name__>()>>
0:00:00 load avg: 1.01 [  8/425] test_posixpath passed
0:00:00 load avg: 1.01 [  9/425] test_setcomps passed
0:00:00 load avg: 1.01 [ 10/425] test_peg_parser passed
0:00:00 load avg: 1.01 [ 11/425] test_pstats passed
0:00:00 load avg: 1.01 [ 12/425] test_dbm passed
0:00:00 load avg: 1.01 [ 13/425] test_aifc passed
0:00:00 load avg: 1.01 [ 14/425] test_marshal passed
0:00:00 load avg: 1.01 [ 15/425] test_unary passed
0:00:00 load avg: 1.01 [ 16/425] test_modulefinder passed
0:00:00 load avg: 1.01 [ 17/425] test_subclassinit passed
0:00:00 load avg: 1.01 [ 18/425] test_builtin passed
0:00:00 load avg: 1.01 [ 19/425] test_site passed
Resource 'https://www.python.org/psf/license/' is not available
0:00:00 load avg: 1.01 [ 20/425] test_tk skipped
test_tk skipped -- No module named '_tkinter'
0:00:00 load avg: 1.01 [ 21/425] test_errno passed
0:00:00 load avg: 1.01 [ 22/425] test_openpty passed
0:00:00 load avg: 1.01 [ 23/425] test_dictcomps passed
0:00:00 load avg: 1.01 [ 24/425] test_repl passed
0:00:00 load avg: 1.01 [ 25/425] test_crypt passed
0:00:00 load avg: 1.01 [ 26/425] test_optparse passed
0:00:00 load avg: 1.01 [ 27/425] test_smtplib passed
0:00:00 load avg: 1.01 [ 28/425] test_unicode_identifiers passed
0:00:00 load avg: 1.01 [ 29/425] test_sys_settrace passed
0:00:00 load avg: 1.01 [ 30/425] test_pprint passed
0:00:00 load avg: 1.01 [ 31/425] test_unpack_ex passed
0:00:00 load avg: 1.01 [ 32/425] test_genericclass passed
0:00:00 load avg: 1.01 [ 33/425] test_finalization passed
0:00:00 load avg: 1.01 [ 34/425] test_poplib passed
0:00:00 load avg: 1.01 [ 35/425] test_types passed
0:00:00 load avg: 1.01 [ 36/425] test_unicode_file_functions passed
0:00:00 load avg: 1.01 [ 37/425] test_locale passed
0:00:00 load avg: 1.01 [ 38/425] test_urllibnet passed
Resource 'www.pythontest.net' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/XXXinvalidXXX' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
0:00:00 load avg: 1.01 [ 39/425] test_atexit passed
0:00:00 load avg: 1.01 [ 40/425] test_gettext passed
0:00:01 load avg: 1.01 [ 41/425] test_py_compile passed
0:00:01 load avg: 1.01 [ 42/425] test_hash passed
0:00:01 load avg: 1.01 [ 43/425] test_exceptions passed
0:00:01 load avg: 1.01 [ 44/425] test_fnmatch passed
0:00:01 load avg: 1.01 [ 45/425] test_bufio passed
0:00:01 load avg: 1.01 [ 46/425] test_curses passed
0:00:01 load avg: 1.01 [ 47/425] test_compare passed
0:00:01 load avg: 1.01 [ 48/425] test_lltrace passed
0:00:01 load avg: 1.01 [ 49/425] test_urllib2net passed
Resource 'http://www.pythontest.net' is not available
Resource 'http://www.pythontest.net' is not available
Resource 'ftp://www.pythontest.net/README' is not available
Resource 'http://www.pythontest.net/redir/with_frag/' is not available
Resource 'http://www.pythontest.net/index.html#frag' is not available
Resource 'ftp://www.pythontest.net/' is not available
Resource 'ftp://www.pythontest.net/' is not available
Resource 'ftp://www.pythontest.net/' is not available
Resource 'ftp://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net' is not available
Resource 'http://www.pythontest.net' is not available
Resource 'http://www.pythontest.net' is not available
Resource 'http://www.pythontest.net' is not available
0:00:01 load avg: 1.01 [ 50/425] test_winreg skipped
test_winreg skipped -- No module named 'winreg'
0:00:01 load avg: 1.01 [ 51/425] test_bdb passed
0:00:01 load avg: 1.01 [ 52/425] test_shelve passed
0:00:01 load avg: 1.01 [ 53/425] test_dict passed
0:00:01 load avg: 1.01 [ 54/425] test_utf8_mode passed
0:00:01 load avg: 1.01 [ 55/425] test_smtpd passed
0:00:01 load avg: 1.01 [ 56/425] test_augassign passed
0:00:01 load avg: 1.01 [ 57/425] test_pkgutil passed
0:00:01 load avg: 1.01 [ 58/425] test_descr passed
0:00:01 load avg: 1.01 [ 59/425] test_minidom passed
0:00:01 load avg: 1.01 [ 60/425] test_tracemalloc passed
0:00:01 load avg: 1.01 [ 61/425] test_weakset passed
0:00:01 load avg: 1.01 [ 62/425] test_mailbox passed
0:00:01 load avg: 1.01 [ 63/425] test_zoneinfo passed
0:00:01 load avg: 1.01 [ 64/425] test_peepholer passed
0:00:01 load avg: 1.01 [ 65/425] test_property passed
0:00:01 load avg: 1.01 [ 66/425] test_sqlite skipped
test_sqlite skipped -- No module named '_sqlite3'
0:00:01 load avg: 1.01 [ 67/425] test_class passed
0:00:01 load avg: 1.01 [ 68/425] test_sched passed
0:00:02 load avg: 1.01 [ 69/425] test_parser passed
0:00:02 load avg: 1.01 [ 70/425] test_ucn passed
0:00:02 load avg: 1.01 [ 71/425] test_time passed
0:00:02 load avg: 1.01 [ 72/425] test_re passed
0:00:02 load avg: 1.01 [ 73/425] test_hashlib passed
0:00:02 load avg: 1.01 [ 74/425] test_ioctl skipped
test_ioctl skipped -- Unable to open /dev/tty
0:00:02 load avg: 1.01 [ 75/425] test_sundry passed
0:00:02 load avg: 1.01 [ 76/425] test_glob passed
0:00:02 load avg: 2.61 [ 77/425] test_context passed
0:00:02 load avg: 2.61 [ 78/425] test_multibytecodec passed
0:00:02 load avg: 2.61 [ 79/425] test_crashers passed
0:00:02 load avg: 2.61 [ 80/425] test_unittest passed
0:00:02 load avg: 2.61 [ 81/425] test_userlist passed
0:00:02 load avg: 2.61 [ 82/425] test_import passed
0:00:02 load avg: 2.61 [ 83/425] test_ast passed
0:00:02 load avg: 2.61 [ 84/425] test_tools passed
0:00:02 load avg: 2.61 [ 85/425] test_bz2 passed
0:00:02 load avg: 2.61 [ 86/425] test_wave passed
0:00:02 load avg: 2.61 [ 87/425] test_codeccallbacks passed
0:00:02 load avg: 2.61 [ 88/425] test_filecmp passed
0:00:02 load avg: 2.61 [ 89/425] test_exception_variations passed
0:00:02 load avg: 2.61 [ 90/425] test_stringprep passed
0:00:02 load avg: 2.61 [ 91/425] test_urlparse passed
0:00:03 load avg: 2.61 [ 92/425] test_codecencodings_kr passed
0:00:03 load avg: 2.61 [ 93/425] test_math passed
0:00:03 load avg: 2.61 [ 94/425] test_code_module passed
0:00:03 load avg: 2.61 [ 95/425] test_descrtut passed
0:00:03 load avg: 2.61 [ 96/425] test_ossaudiodev skipped (resource denied)
test_ossaudiodev skipped -- Use of the 'audio' resource not enabled
0:00:03 load avg: 2.61 [ 97/425] test_dis passed
0:00:03 load avg: 2.61 [ 98/425] test_httpservers passed
0:00:03 load avg: 2.61 [ 99/425] test_int passed
0:00:03 load avg: 2.61 [100/425] test_tix skipped
test_tix skipped -- No module named '_tkinter'
0:00:03 load avg: 2.61 [101/425] test_msilib skipped
test_msilib skipped -- No module named '_msi'
0:00:03 load avg: 2.61 [102/425] test_dynamicclassattribute passed
0:00:03 load avg: 2.61 [103/425] test_zipfile64 skipped (resource denied)
test_zipfile64 skipped -- test requires loads of disk-space bytes and a long time to run
0:00:03 load avg: 2.61 [104/425] test_bigaddrspace passed
0:00:03 load avg: 2.61 [105/425] test_global passed
0:00:03 load avg: 2.61 [106/425] test_sort passed
0:00:03 load avg: 2.61 [107/425] test_future3 passed
0:00:03 load avg: 2.61 [108/425] test_dict_version passed
0:00:03 load avg: 2.61 [109/425] test_calendar passed
0:00:03 load avg: 2.61 [110/425] test_xmlrpc_net passed
0:00:03 load avg: 2.61 [111/425] test_codecencodings_iso2022 passed
0:00:03 load avg: 2.61 [112/425] test_long passed
0:00:03 load avg: 2.61 [113/425] test_doctest passed
0:00:03 load avg: 2.61 [114/425] test_nis skipped
test_nis skipped -- No module named 'nis'
0:00:03 load avg: 2.61 [115/425] test_future5 passed
0:00:03 load avg: 2.61 [116/425] test_clinic passed
0:00:03 load avg: 2.61 [117/425] test_argparse passed
0:00:03 load avg: 2.61 [118/425] test_strtod passed
0:00:03 load avg: 2.61 [119/425] test_binascii passed
0:00:03 load avg: 2.61 [120/425] test_reprlib passed
0:00:03 load avg: 2.61 [121/425] test_pkg passed
0:00:03 load avg: 2.61 [122/425] test_pyexpat passed
0:00:03 load avg: 2.61 [123/425] test_support passed
0:00:03 load avg: 2.61 [124/425] test_abstract_numbers passed
0:00:03 load avg: 2.61 [125/425] test_iter passed
0:00:03 load avg: 2.61 [126/425] test_mimetypes passed
0:00:03 load avg: 2.61 [127/425] test_funcattrs passed
0:00:03 load avg: 2.61 [128/425] test_threadedtempfile passed
0:00:03 load avg: 2.61 [129/425] test_configparser passed
0:00:03 load avg: 2.61 [130/425] test_wsgiref passed
0:00:03 load avg: 2.61 [131/425] test_stat passed
0:00:03 load avg: 2.61 [132/425] test_string passed
0:00:03 load avg: 2.61 [133/425] test_codecencodings_jp passed
0:00:03 load avg: 2.61 [134/425] test_raise passed
0:00:03 load avg: 2.61 [135/425] test_file_eintr passed
0:00:04 load avg: 2.61 [136/425] test_future passed
0:00:04 load avg: 2.61 [137/425] test_dbm_dumb passed
0:00:04 load avg: 2.61 [138/425] test_copy passed
0:00:04 load avg: 2.61 [139/425] test_dbm_ndbm passed
0:00:04 load avg: 2.61 [140/425] test_fileinput passed
0:00:04 load avg: 2.61 [141/425] test_posix passed
0:00:04 load avg: 2.61 [142/425] test_unicode_file passed
0:00:04 load avg: 2.61 [143/425] test___future__ passed
0:00:04 load avg: 2.61 [144/425] test_getargs2 passed
0:00:04 load avg: 2.61 [145/425] test_strptime passed
0:00:04 load avg: 2.61 [146/425] test_heapq passed
0:00:04 load avg: 2.61 [147/425] test_abc passed
0:00:04 load avg: 2.61 [148/425] test_zlib passed
0:00:04 load avg: 2.61 [149/425] test_webbrowser passed
0:00:04 load avg: 2.61 [150/425] test_format passed
0:00:04 load avg: 2.61 [151/425] test_spwd passed
0:00:04 load avg: 2.61 [152/425] test_difflib passed
0:00:04 load avg: 2.61 [153/425] test_cprofile passed
0:00:04 load avg: 2.61 [154/425] test_imghdr passed
0:00:04 load avg: 2.61 [155/425] test_ttk_textonly skipped
test_ttk_textonly skipped -- No module named '_tkinter'
0:00:05 load avg: 2.61 [156/425] test_ctypes passed
0:00:05 load avg: 2.61 [157/425] test_opcodes passed
0:00:05 load avg: 2.61 [158/425] test_lzma passed
0:00:05 load avg: 2.61 [159/425] test_audit passed
0:00:05 load avg: 2.61 [160/425] test_extcall passed
0:00:05 load avg: 2.61 [161/425] test_doctest2 passed
0:00:05 load avg: 2.61 [162/425] test___all__ passed
0:00:05 load avg: 2.61 [163/425] test_popen passed
0:00:05 load avg: 2.61 [164/425] test_pyclbr passed
0:00:05 load avg: 2.61 [165/425] test_uuid passed
0:00:05 load avg: 2.61 [166/425] test_urllib_response passed
0:00:05 load avg: 2.61 [167/425] test_defaultdict passed
0:00:05 load avg: 2.61 [168/425] test_trace passed
0:00:05 load avg: 2.61 [169/425] test_ensurepip passed
0:00:05 load avg: 2.61 [170/425] test_zipimport_support passed
0:00:05 load avg: 2.61 [171/425] test_fstring passed
0:00:05 load avg: 2.61 [172/425] test_genexps passed
0:00:05 load avg: 2.61 [173/425] test_memoryio passed
0:00:05 load avg: 2.61 [174/425] test_print passed
0:00:05 load avg: 2.61 [175/425] test_compile passed
0:00:05 load avg: 2.61 [176/425] test_random passed
0:00:05 load avg: 2.61 [177/425] test_readline passed
0:00:05 load avg: 2.61 [178/425] test_plistlib passed
0:00:06 load avg: 2.61 [179/425] test_cmath passed
0:00:06 load avg: 2.61 [180/425] test_htmlparser passed
0:00:06 load avg: 2.61 [181/425] test_codeop passed
0:00:06 load avg: 2.61 [182/425] test_memoryview passed
0:00:06 load avg: 2.61 [183/425] test_urllib passed
0:00:06 load avg: 2.61 [184/425] test_genericpath passed
0:00:06 load avg: 2.61 [185/425] test_pickletools passed
0:00:06 load avg: 2.61 [186/425] test_urllib2_localnet passed
0:00:06 load avg: 2.61 [187/425] test_string_literals passed
0:00:06 load avg: 2.61 [188/425] test_richcmp passed
0:00:06 load avg: 2.61 [189/425] test_wait4 passed
0:00:06 load avg: 2.61 [190/425] test_picklebuffer passed
0:00:06 load avg: 2.61 [191/425] test_grp passed
0:00:06 load avg: 2.61 [192/425] test_codecencodings_tw passed
0:00:06 load avg: 2.61 [193/425] test_distutils passed
0:00:06 load avg: 2.61 [194/425] test_hmac passed
0:00:06 load avg: 2.61 [195/425] test_ttk_guionly skipped
test_ttk_guionly skipped -- No module named '_tkinter'
0:00:06 load avg: 2.61 [196/425] test_fcntl passed
0:00:06 load avg: 2.61 [197/425] test_itertools passed
0:00:07 load avg: 2.61 [198/425] test_codecs passed
0:00:07 load avg: 2.61 [199/425] test_listcomps passed
0:00:07 load avg: 2.61 [200/425] test_sys_setprofile passed
0:00:07 load avg: 2.61 [201/425] test_bigmem passed
0:00:07 load avg: 2.61 [202/425] test_struct passed
0:00:07 load avg: 2.61 [203/425] test_fileio passed
0:00:07 load avg: 2.61 [204/425] test_typing passed
0:00:07 load avg: 3.69 [205/425] test_binop passed
0:00:07 load avg: 3.69 [206/425] test_eintr passed
0:00:07 load avg: 3.69 [207/425] test_startfile skipped
test_startfile skipped -- object <module 'os' from '/sources/Python-3.9.1/Lib/os.py'> has no attribute 'startfile'
0:00:07 load avg: 3.69 [208/425] test_base64 passed
0:00:07 load avg: 3.69 [209/425] test_cmd_line_script passed
0:00:07 load avg: 3.69 [210/425] test_contains passed
0:00:07 load avg: 3.69 [211/425] test__locale passed
0:00:07 load avg: 3.69 [212/425] test_thread passed
0:00:07 load avg: 3.69 [213/425] test_compileall passed
0:00:07 load avg: 3.69 [214/425] test_textwrap passed
0:00:07 load avg: 3.69 [215/425] test_fractions passed
0:00:07 load avg: 3.69 [216/425] test_codecmaps_tw passed
0:00:07 load avg: 3.69 [217/425] test_getopt passed
0:00:07 load avg: 3.69 [218/425] test__xxsubinterpreters passed
0:00:07 load avg: 3.69 [219/425] test_httplib passed
Resource 'self-signed.pythontest.net' is not available
Resource 'self-signed.pythontest.net' is not available
Resource 'self-signed.pythontest.net' is not available
Resource 'self-signed.pythontest.net' is not available
Resource 'www.python.org' is not available
0:00:07 load avg: 3.69 [220/425] test_pwd passed
0:00:07 load avg: 3.69 [221/425] test_file passed
0:00:08 load avg: 3.69 [222/425] test_yield_from passed
0:00:08 load avg: 3.69 [223/425] test_operator passed
0:00:08 load avg: 3.69 [224/425] test_isinstance passed
0:00:08 load avg: 3.69 [225/425] test_linecache passed
0:00:08 load avg: 3.69 [226/425] test_codecmaps_cn passed
0:00:08 load avg: 3.69 [227/425] test_dynamic passed
0:00:08 load avg: 3.69 [228/425] test_frozen passed
0:00:08 load avg: 3.69 [229/425] test_ipaddress passed
0:00:08 load avg: 3.69 [230/425] test_xml_etree_c passed
0:00:08 load avg: 3.69 [231/425] test_future4 passed
0:00:08 load avg: 3.69 [232/425] test_float passed
0:00:08 load avg: 3.69 [233/425] test_flufl passed
0:00:08 load avg: 3.69 [234/425] test_slice passed
0:00:08 load avg: 3.69 [235/425] test_longexp passed
0:00:08 load avg: 3.69 [236/425] test_script_helper passed
0:00:08 load avg: 3.69 [237/425] test_numeric_tower passed
0:00:08 load avg: 3.69 [238/425] test_audioop passed
0:00:08 load avg: 3.69 [239/425] test_fork1 passed
0:00:08 load avg: 3.69 [240/425] test_threadsignals passed
0:00:08 load avg: 3.69 [241/425] test_index passed
0:00:09 load avg: 3.69 [242/425] test_pathlib passed
0:00:09 load avg: 3.69 [243/425] test_utf8source passed
0:00:09 load avg: 3.69 [244/425] test_array passed
0:00:09 load avg: 3.69 [245/425] test_kqueue skipped
test_kqueue skipped -- test works only on BSD
0:00:09 load avg: 3.69 [246/425] test_tuple passed
0:00:09 load avg: 3.69 [247/425] test_graphlib passed
0:00:09 load avg: 3.69 [248/425] test_eof passed
0:00:09 load avg: 3.69 [249/425] test_html passed
0:00:09 load avg: 3.69 [250/425] test_pulldom passed
0:00:09 load avg: 3.69 [251/425] test_os passed
0:00:09 load avg: 3.69 [252/425] test_structmembers passed
0:00:09 load avg: 3.69 [253/425] test_netrc passed
0:00:09 load avg: 3.69 [254/425] test_zipfile passed
0:00:09 load avg: 3.69 [255/425] test_traceback passed
0:00:09 load avg: 3.69 [256/425] test_buffer passed
0:00:09 load avg: 3.69 [257/425] test_tcl skipped
test_tcl skipped -- No module named '_tkinter'
0:00:09 load avg: 3.69 [258/425] test_structseq passed
0:00:09 load avg: 3.69 [259/425] test_typechecks passed
0:00:10 load avg: 3.69 [260/425] test_cmd passed
0:00:10 load avg: 3.69 [261/425] test_symbol passed
0:00:10 load avg: 3.69 [262/425] test_codecmaps_kr passed
0:00:10 load avg: 3.69 [263/425] test_pdb passed
0:00:10 load avg: 3.69 [264/425] test_int_literal passed
0:00:10 load avg: 3.69 [265/425] test_codecencodings_cn passed
0:00:10 load avg: 3.69 [266/425] test_runpy passed
0:00:10 load avg: 3.69 [267/425] test_symtable passed
0:00:10 load avg: 3.69 [268/425] test_generators passed
0:00:11 load avg: 3.69 [269/425] test_exception_hierarchy passed
0:00:11 load avg: 3.69 [270/425] test__opcode passed
0:00:11 load avg: 3.69 [271/425] test_contextlib passed
0:00:11 load avg: 3.69 [272/425] test_metaclass passed
0:00:11 load avg: 3.69 [273/425] test_email passed
0:00:11 load avg: 3.69 [274/425] test_pickle passed
0:00:11 load avg: 3.69 [275/425] test_generator_stop passed
0:00:11 load avg: 3.69 [276/425] test_threading_local passed
0:00:11 load avg: 3.69 [277/425] test_pow passed
0:00:11 load avg: 3.69 [278/425] test_resource passed
0:00:11 load avg: 3.69 [279/425] test_copyreg passed
0:00:11 load avg: 3.69 [280/425] test_mailcap passed
0:00:12 load avg: 3.69 [281/425] test_datetime passed
0:00:12 load avg: 3.69 [282/425] test_sax passed
0:00:12 load avg: 3.69 [283/425] test_grammar passed
0:00:12 load avg: 3.69 [284/425] test_xxtestfuzz passed
0:00:12 load avg: 3.69 [285/425] test_largefile passed
0:00:12 load avg: 3.69 [286/425] test_ordered_dict passed
0:00:12 load avg: 3.69 [287/425] test_gdb skipped
test_gdb skipped -- Couldn't find gdb on the path
0:00:12 load avg: 3.69 [288/425] test_syntax passed
0:00:12 load avg: 3.69 [289/425] test_dictviews passed
0:00:12 load avg: 4.83 [290/425] test_check_c_globals passed
0:00:12 load avg: 4.83 [291/425] test_functools passed
0:00:12 load avg: 4.83 [292/425] test_code passed
0:00:12 load avg: 4.83 [293/425] test_gzip passed
0:00:12 load avg: 4.83 [294/425] test_platform passed
0:00:12 load avg: 4.83 [295/425] test_sys passed
0:00:13 load avg: 4.83 [296/425] test_docxmlrpc passed
0:00:13 load avg: 4.83 [297/425] test_turtle skipped
test_turtle skipped -- No module named '_tkinter'
0:00:13 load avg: 4.83 [298/425] test_tempfile passed
0:00:13 load avg: 4.83 [299/425] test_osx_env passed
0:00:13 load avg: 4.83 [300/425] test_coroutines passed
0:00:13 load avg: 4.83 [301/425] test_dtrace passed
0:00:13 load avg: 4.83 [302/425] test_shutil passed
0:00:13 load avg: 4.83 [303/425] test_tarfile passed
0:00:13 load avg: 4.83 [304/425] test_nntplib passed
Resource 'news.trigofacile.com' is not available
Resource 'nntp.aioe.org' is not available
0:00:13 load avg: 4.83 [305/425] test_bool passed
0:00:14 load avg: 4.83 [306/425] test_imp passed
0:00:14 load avg: 4.83 [307/425] test_zipapp passed
0:00:14 load avg: 4.83 [308/425] test_regrtest passed
0:00:14 load avg: 4.83 [309/425] test_asynchat passed
0:00:14 load avg: 4.83 [310/425] test_robotparser passed
Resource 'http://www.pythontest.net/' is not available
0:00:14 load avg: 4.83 [311/425] test_type_comments passed
0:00:14 load avg: 4.83 [312/425] test_set passed
0:00:14 load avg: 4.83 [313/425] test_profile passed
0:00:14 load avg: 4.83 [314/425] test_winconsoleio skipped
test_winconsoleio skipped -- test only relevant on win32
0:00:14 load avg: 4.83 [315/425] test_epoll passed
0:00:14 load avg: 4.83 [316/425] test_named_expressions passed
0:00:14 load avg: 4.83 [317/425] test_binhex passed
0:00:14 load avg: 4.83 [318/425] test_unpack passed
0:00:14 load avg: 4.83 [319/425] test_baseexception passed
0:00:14 load avg: 4.83 [320/425] test_venv passed
0:00:14 load avg: 4.83 [321/425] test_keyword passed
0:00:14 load avg: 4.83 [322/425] test_list passed
0:00:14 load avg: 4.83 [323/425] test_cgi passed
0:00:15 load avg: 4.83 [324/425] test_enumerate passed
0:00:15 load avg: 4.83 [325/425] test_warnings passed
0:00:15 load avg: 4.83 [326/425] test_weakref passed
0:00:15 load avg: 4.83 [327/425] test_frame passed
0:00:15 load avg: 4.83 [328/425] test_ftplib passed
0:00:15 load avg: 4.83 [329/425] test_sndhdr passed
0:00:15 load avg: 4.83 [330/425] test_inspect passed
0:00:15 load avg: 4.83 [331/425] test_ntpath passed
0:00:15 load avg: 4.83 [332/425] test_c_locale_coercion passed
0:00:15 load avg: 4.83 [333/425] test_multiprocessing_main_handling passed
0:00:15 load avg: 4.83 [334/425] test_xml_dom_minicompat passed
0:00:15 load avg: 4.83 [335/425] test_sysconfig passed
0:00:15 load avg: 4.83 [336/425] test_userstring passed
0:00:15 load avg: 4.83 [337/425] test_bisect passed
0:00:15 load avg: 4.83 [338/425] test_deque passed
0:00:15 load avg: 4.83 [339/425] test_quopri passed
0:00:15 load avg: 4.83 [340/425] test_codecmaps_jp passed
0:00:16 load avg: 4.83 [341/425] test_complex passed
0:00:16 load avg: 4.83 [342/425] test_devpoll skipped
test_devpoll skipped -- test works only on Solaris OS family
0:00:16 load avg: 4.83 [343/425] test_json passed
0:00:16 load avg: 4.83 [344/425] test__osx_support passed
0:00:16 load avg: 4.83 [345/425] test_colorsys passed
0:00:16 load avg: 4.83 [346/425] test_cgitb passed
0:00:16 load avg: 4.83 [347/425] test_queue passed
0:00:16 load avg: 4.83 [348/425] test_secrets passed
0:00:16 load avg: 4.83 [349/425] test_smtpnet passed
Resource 'smtp.gmail.com' is not available
Resource 'smtp.gmail.com' is not available
Resource 'smtp.gmail.com' is not available
Resource 'smtp.gmail.com' is not available
Resource 'smtp.gmail.com' is not available
0:00:16 load avg: 4.83 [350/425] test_mmap passed
0:00:16 load avg: 4.83 [351/425] test_tabnanny passed
0:00:16 load avg: 4.83 [352/425/1] test_unicodedata failed
test test_unicodedata failed -- Traceback (most recent call last):
  File "/sources/Python-3.9.1/Lib/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/Python-3.9.1/Lib/test/test_unicodedata.py", line 329, in test_normalization
    testdata = open_urlresource(TESTDATAURL, encoding="utf-8",
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/Python-3.9.1/Lib/test/test_unicodedata.py", line 335, in test_normalization
    self.fail(f"Could not retrieve {TESTDATAURL}")
AssertionError: Could not retrieve http://www.pythontest.net/unicode/13.0.0/NormalizationTest.txt
0:00:16 load avg: 4.83 [353/425/1] test_http_cookies passed
0:00:16 load avg: 4.83 [354/425/1] test_with passed
0:00:16 load avg: 4.83 [355/425/1] test_charmapcodec passed
0:00:16 load avg: 4.83 [356/425/1] test_decorators passed
0:00:17 load avg: 4.83 [357/425/1] test_asyncgen passed
0:00:17 load avg: 4.83 [358/425/1] test_zipimport passed
0:00:17 load avg: 5.25 [359/425/1] test_genericalias passed
0:00:18 load avg: 5.25 [360/425/1] test_socketserver passed
0:00:18 load avg: 5.25 [361/425/1] test_unicode passed
0:00:18 load avg: 5.25 [362/425/1] test_getpass passed
0:00:18 load avg: 5.25 [363/425/1] test_dbm_gnu passed
0:00:18 load avg: 5.25 [364/425/1] test_ssl passed
/sources/Python-3.9.1/Lib/test/support/__init__.py:3105: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50585), raddr=('127.0.0.1', 43116)>
  del self.thread
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Resource 'ipv6.google.com' is not available
Resource 'self-signed.pythontest.net' is not available
0:00:18 load avg: 5.25 [365/425/1] test_winsound skipped (resource denied)
test_winsound skipped -- Use of the 'audio' resource not enabled
0:00:18 load avg: 5.25 [366/425/1] test_enum passed
0:00:18 load avg: 5.25 [367/425/1] test_syslog passed
0:00:18 load avg: 5.25 [368/425/1] test_pty passed
0:00:18 load avg: 5.25 [369/425/1] test_collections passed
0:00:19 load avg: 5.25 [370/425/1] test_embed passed
0:00:19 load avg: 5.25 [371/425/1] test_xmlrpc passed
0:00:19 load avg: 5.25 [372/425/1] test_source_encoding passed
0:00:20 load avg: 5.25 [373/425/1] test_asyncore passed
0:00:20 load avg: 5.25 [374/425/1] test_wait3 passed
0:00:20 load avg: 5.25 [375/425/1] test_bytes passed
0:00:20 load avg: 5.25 [376/425/1] test_csv passed
0:00:20 load avg: 5.25 [377/425/1] test_logging passed
0:00:20 load avg: 5.25 [378/425/1] test_scope passed
0:00:21 load avg: 5.25 [379/425/1] test_sunau passed
0:00:21 load avg: 5.25 [380/425/1] test_timeout passed
Resource 'www.python.org.' is not available
Resource 'www.python.org.' is not available
Resource 'www.python.org.' is not available
Resource 'www.python.org.' is not available
Resource 'www.python.org.' is not available
/sources/Python-3.9.1/Lib/test/support/__init__.py:1438: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  gc.collect()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/sources/Python-3.9.1/Lib/test/support/__init__.py:1438: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  gc.collect()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/sources/Python-3.9.1/Lib/test/support/__init__.py:1438: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  gc.collect()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/sources/Python-3.9.1/Lib/test/support/__init__.py:1438: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  gc.collect()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/sources/Python-3.9.1/Lib/test/support/__init__.py:1438: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  gc.collect()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
0:00:21 load avg: 5.25 [381/425/1] test_dataclasses passed
0:00:21 load avg: 5.25 [382/425/1] test_uu passed
0:00:21 load avg: 5.25 [383/425/1] test_asdl_parser passed
0:00:21 load avg: 5.25 [384/425/1] test_select passed
0:00:21 load avg: 5.25 [385/425/1] test_http_cookiejar passed
0:00:21 load avg: 5.25 [386/425/1] test_telnetlib passed
0:00:21 load avg: 5.25 [387/425/1] test_xml_etree passed
0:00:21 load avg: 5.25 [388/425/1] test_decimal passed
0:00:21 load avg: 5.25 [389/425/1] test_urllib2 passed
Resource 'http://www.example.com/' is not available
0:00:21 load avg: 5.25 [390/425/1] test_shlex passed
0:00:21 load avg: 5.25 [391/425/1] test_range passed
0:00:21 load avg: 5.25 [392/425/1] test_module passed
0:00:21 load avg: 5.25 [393/425/1] test_pipes passed
0:00:21 load avg: 5.25 [394/425/1] test_timeit passed
0:00:21 load avg: 5.25 [395/425/1] test_userdict passed
0:00:21 load avg: 5.25 [396/425/1] test_univnewlines passed
0:00:21 load avg: 5.25 [397/425/1] test_rlcompleter passed
0:00:21 load avg: 5.25 [398/425/1] test_call passed
0:00:22 load avg: 5.25 [399/425/1] test_codecmaps_hk passed
0:00:22 load avg: 5.25 [400/425/1] test_iterlen passed
0:00:22 load avg: 5.25 [401/425/1] test_strftime passed
0:00:22 load avg: 5.25 [402/425/1] test_cmd_line passed
0:00:22 load avg: 5.39 [403/425/1] test_importlib passed
0:00:22 load avg: 5.39 [404/425/1] test_imaplib passed
0:00:23 load avg: 5.39 [405/425/1] test_socket passed
Resource 'python.org' is not available
0:00:23 load avg: 5.39 [406/425/1] test_gc passed
0:00:23 load avg: 5.39 [407/425/1] test_statistics passed
0:00:26 load avg: 5.39 [408/425/1] test_capi passed
0:00:27 load avg: 5.76 [409/425/1] test_poll passed
0:00:31 load avg: 5.76 [410/425/1] test_subprocess passed
/sources/Python-3.9.1/Lib/subprocess.py:1048: ResourceWarning: subprocess 4926 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
0:00:31 load avg: 5.76 [411/425/1] test_threading passed
0:00:32 load avg: 5.70 [412/425/1] test_selectors passed
0:00:33 load avg: 5.70 [413/425/1] test_unparse passed -- running: test_asyncio (30.8 sec)
0:00:35 load avg: 5.70 [414/425/1] test_lib2to3 passed -- running: test_peg_generator (30.2 sec), test_pydoc (30.8 sec), test_asyncio (32.8 sec)
0:00:36 load avg: 5.70 [415/425/1] test_pydoc passed (31.3 sec) -- running: test_peg_generator (30.8 sec), test_concurrent_futures (30.1 sec), test_io (30.4 sec), test_asyncio (33.3 sec)
0:00:38 load avg: 5.48 [416/425/1] test_tokenize passed -- running: test_peg_generator (32.9 sec), test_multiprocessing_spawn (31.7 sec), test_concurrent_futures (32.2 sec), test_io (32.5 sec), test_asyncio (35.5 sec)
0:00:39 load avg: 5.48 [417/425/1] test_faulthandler passed -- running: test_peg_generator (33.8 sec), test_multiprocessing_spawn (32.5 sec), test_concurrent_futures (33.1 sec), test_io (33.4 sec), test_asyncio (36.3 sec)
0:00:39 load avg: 5.48 [418/425/1] test_io passed (33.5 sec) -- running: test_peg_generator (34.1 sec), test_multiprocessing_spawn (32.8 sec), test_concurrent_futures (33.4 sec), test_asyncio (36.6 sec)
0:00:52 load avg: 5.27 [419/425/1] test_asyncio passed (49.4 sec) -- running: test_peg_generator (47.0 sec), test_multiprocessing_spawn (45.7 sec), test_signal (39.7 sec), test_concurrent_futures (46.3 sec), test_multiprocessing_forkserver (38.4 sec), test_multiprocessing_fork (35.6 sec)
0:00:59 load avg: 4.76 [420/425/1] test_signal passed (46.5 sec) -- running: test_peg_generator (53.9 sec), test_multiprocessing_spawn (52.6 sec), test_concurrent_futures (53.1 sec), test_multiprocessing_forkserver (45.3 sec), test_multiprocessing_fork (42.4 sec)
0:01:07 load avg: 4.46 [421/425/1] test_multiprocessing_fork passed (50.6 sec) -- running: test_peg_generator (1 min 2 sec), test_multiprocessing_spawn (1 min), test_concurrent_futures (1 min 1 sec), test_multiprocessing_forkserver (53.5 sec)
0:01:08 load avg: 4.18 [422/425/1] test_multiprocessing_spawn passed (1 min 1 sec) -- running: test_peg_generator (1 min 2 sec), test_concurrent_futures (1 min 2 sec), test_multiprocessing_forkserver (54.3 sec)
0:01:14 load avg: 3.92 [423/425/1] test_multiprocessing_forkserver passed (1 min) -- running: test_peg_generator (1 min 8 sec), test_concurrent_futures (1 min 8 sec)
0:01:32 load avg: 3.28 [424/425/1] test_peg_generator passed (1 min 26 sec) -- running: test_concurrent_futures (1 min 26 sec)
0:02:02 load avg: 2.04 running: test_concurrent_futures (1 min 56 sec)
0:02:27 load avg: 1.34 [425/425/1] test_concurrent_futures passed (2 min 21 sec)

== Tests result: FAILURE ==

404 tests OK.

1 test failed:
    test_unicodedata

20 tests skipped:
    test_devpoll test_gdb test_idle test_ioctl test_kqueue test_msilib
    test_nis test_ossaudiodev test_sqlite test_startfile test_tcl
    test_tix test_tk test_ttk_guionly test_ttk_textonly test_turtle
    test_winconsoleio test_winreg test_winsound test_zipfile64
0:02:27 load avg: 1.34
0:02:27 load avg: 1.34 Re-running failed tests in verbose mode
0:02:27 load avg: 1.34 Re-running test_unicodedata in verbose mode
test_bug_834676 (test.test_unicodedata.NormalizationTest) ... ok
test_edge_cases (test.test_unicodedata.NormalizationTest) ... ok
test_normalization (test.test_unicodedata.NormalizationTest) ... 	fetching http://www.pythontest.net/unicode/13.0.0/NormalizationTest.txt ...
FAIL
test_bidirectional (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_category (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_combining (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_decimal (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_decomposition (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_digit (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_east_asian_width (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_east_asian_width_9_0_changes (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_function_checksum (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_issue10254 (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_issue29456 (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_mirrored (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_numeric (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_pr29 (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_method_checksum (test.test_unicodedata.UnicodeMethodsTest) ... ok
test_bug_1704793 (test.test_unicodedata.UnicodeMiscTest) ... ok
test_bug_4971 (test.test_unicodedata.UnicodeMiscTest) ... ok
test_bug_5828 (test.test_unicodedata.UnicodeMiscTest) ... ok
test_decimal_numeric_consistent (test.test_unicodedata.UnicodeMiscTest) ... ok
test_digit_numeric_consistent (test.test_unicodedata.UnicodeMiscTest) ... ok
test_failed_import_during_compiling (test.test_unicodedata.UnicodeMiscTest) ... ok
test_linebreak_7643 (test.test_unicodedata.UnicodeMiscTest) ... ok
test_ucd_510 (test.test_unicodedata.UnicodeMiscTest) ... test test_unicodedata failed
ok

======================================================================
FAIL: test_normalization (test.test_unicodedata.NormalizationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sources/Python-3.9.1/Lib/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/Python-3.9.1/Lib/test/test_unicodedata.py", line 329, in test_normalization
    testdata = open_urlresource(TESTDATAURL, encoding="utf-8",
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/Python-3.9.1/Lib/test/test_unicodedata.py", line 335, in test_normalization
    self.fail(f"Could not retrieve {TESTDATAURL}")
AssertionError: Could not retrieve http://www.pythontest.net/unicode/13.0.0/NormalizationTest.txt

----------------------------------------------------------------------

Ran 26 tests in 8.202s

FAILED (failures=1)
1 test failed again:
    test_unicodedata

== Tests result: FAILURE then FAILURE ==

404 tests OK.

1 test failed:
    test_unicodedata

20 tests skipped:
    test_devpoll test_gdb test_idle test_ioctl test_kqueue test_msilib
    test_nis test_ossaudiodev test_sqlite test_startfile test_tcl
    test_tix test_tk test_ttk_guionly test_ttk_textonly test_turtle
    test_winconsoleio test_winreg test_winsound test_zipfile64

1 re-run test:
    test_unicodedata

Total duration: 2 min 35 sec
Tests result: FAILURE then FAILURE
make[1]: *** [Makefile:1199: test] Error 2
make[1]: Leaving directory '/sources/Python-3.9.1'
